<?php

/* $Id: en.lang.php 4606 2011-05-09 21:41:38Z denis $ */
define("NETCAT_MODULE_SETUP_FORUM2", "Forum");

define("NETCAT_MODULE_FORUM2_DESCRIPTION", "Forum: new version.");

define("NETCAT_MODULE_FORUM2_FORUM_TOPIC_TYPE", "Topics types");
define("NETCAT_MODULE_FORUM2_FORUM_TOPIC_TYPE_SIMPLE", "simple");
define("NETCAT_MODULE_FORUM2_FORUM_TOPIC_TYPE_IMPORTANT", "important");
define("NETCAT_MODULE_FORUM2_FORUM_TOPIC_TYPE_ADVERTISEMENT", "advertisement");
define("NETCAT_MODULE_FORUM2_FORUM_TOPIC_TYPE_CLOSED", "closed");

define("NETCAT_MODULE_FORUM2_FORUM_REPLY", "Reply to the topic");

// components constants
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_LEGEND", "Append new forum");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_CHECKED", "switch on the forum");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_KEYWORD", "Forum keyword");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_NAME", "Forum name");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_DESCRIPTION", "Forum description");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_GROUP", "Forum category");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_TOPIC_KEYWORD", "\"Topics\" component keyword");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_TOPIC_NAME", "\"Topics\" component name");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_REPLY_KEYWORD", "\"Replies\" component keyword");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_REPLY_NAME", "\"Replies\" component name");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_TOPIC_RSS_KEYWORD", "\"Topics RSS\" component keyword");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_TOPIC_RSS_NAME", "\"Topics RSS\" component name");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_REPLY_RSS_KEYWORD", "\"Replies RSS\" component keyword");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_REPLY_RSS_NAME", "\"Replies RSS\" component name");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_DEFAULT_TOPIC_KEYWORD", "topic");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_DEFAULT_TOPIC_NAME", "Topics");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_DEFAULT_REPLY_KEYWORD", "reply");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_DEFAULT_REPLY_NAME", "Replies");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_DEFAULT_PARENT_RSS_KEYWORD", "rss");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_DEFAULT_PARENT_RSS_NAME", "RSS");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_DEFAULT_TOPIC_RSS_KEYWORD", "rss");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_DEFAULT_TOPIC_RSS_NAME", "Topics RSS");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_DEFAULT_REPLY_RSS_KEYWORD", "replyrss");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_DEFAULT_REPLY_RSS_NAME", "Replies RSS");

define("NETCAT_MODULE_FORUM2_USER_GUEST", "Guest");

define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_REQFIELDS", "Field <b>\"".NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_KEYWORD."\"</b> and <b>\"".NETCAT_MODULE_FORUM2_COMPONENT_FORUM_FIELD_NAME."\" required</b>");

define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_ERROR_CREATE", "Error establishing a forum!");
define("NETCAT_MODULE_FORUM2_COMPONENT_FORUM_ERROR_EXIST", "Forum with the keyword <b>\"%s\"</b> already exists!");

define("NETCAT_MODULE_FORUM2_COMPONENT_INSIDE_ADMIN_RSS", "RSS feed is not available in edit mode, <a href='%s' target='_blank'>view RSS</a>");

define("NETCAT_MODULE_FORUM2_COMPONENT_REPLIES_EDIT_IN_PLACE", "Responses to the topic easier to edit, open the desired topic.");
define("NETCAT_MODULE_FORUM2_COMPONENT_REPLIES_SOURCE", "Source message");

define("NETCAT_MODULE_FORUM2_COMPONENT_MESSAGE_PREVIEW", "Preview");

define("NETCAT_MODULE_FORUM2_COMPONENT_TOPIC_UPDATED", "Topic updated.");
define("NETCAT_MODULE_FORUM2_COMPONENT_REPLY_UPDATED", "Reply changed.");

define("NETCAT_MODULE_FORUM2_COMPONENT_TOPIC_CLOSED", "Topic closed.");

define("NETCAT_MODULE_FORUM2_COMPONENT_TOPIC_ADDED", "Topic added.");
define("NETCAT_MODULE_FORUM2_COMPONENT_TOPIC_ADDED_MODERATION", "The new topic will be added after checking the forum moderator.");
define("NETCAT_MODULE_FORUM2_COMPONENT_RETURN_TO_THE_FORUM", "Return to the forum");

define("NETCAT_MODULE_FORUM2_COMPONENT_REPLY_ADDED", "Reply to topic added.");
define("NETCAT_MODULE_FORUM2_COMPONENT_REPLY_ADDED_MODERATION", "The answer to the topic will be added after checking the forum moderator.");
define("NETCAT_MODULE_FORUM2_COMPONENT_RETURN_TO_THE_TOPIC", "Return to the topic");

// module admin
define("NETCAT_MODULE_FORUM2_ADMIN_TEMPLATE_CONVERTER_TAB", "Old Versions Converter");
define("NETCAT_MODULE_FORUM2_ADMIN_TEMPLATE_SETTINGS_TAB", "Forum settings");

define("NETCAT_MODULE_FORUM2_ADMIN_SETTINGS_FORUM_LIST", "Forum list");
define("NETCAT_MODULE_FORUM2_ADMIN_SETTINGS_GROUPS_SETTINGS", "Manage categories");
define("NETCAT_MODULE_FORUM2_ADMIN_SETTINGS_GROUP_NEW", "-- new category --");
define("NETCAT_MODULE_FORUM2_ADMIN_SETTINGS_GROUP_FORUM", "Categories forum");
define("NETCAT_MODULE_FORUM2_ADMIN_SETTINGS_GROUP_NAME", "Category name");
define("NETCAT_MODULE_FORUM2_ADMIN_SETTINGS_GROUP_PRIORITY", "Priority");
define("NETCAT_MODULE_FORUM2_ADMIN_SETTINGS_GROUP_DESCRIPTION", "Category description");
define("NETCAT_MODULE_FORUM2_ADMIN_SETTINGS_GROUP_DELETE", "delete category");
define("NETCAT_MODULE_FORUM2_ADMIN_SETTINGS_SAVE", "Save");
define("NETCAT_MODULE_FORUM2_ADMIN_SETTINGS_NO_FORUMS_FOUND", "no forums found");

define("NETCAT_MODULE_FORUM2_ADMIN_SAVE_OK", "Settings updated");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERTER_RETURN_BUTTON", "Back");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERTER_SAVE_BUTTON_3", "Select site");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERTER_SAVE_BUTTON_4", "Convert");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERTER_SELECT_CATALOGUE", "Site selection");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERTER_SELECT_SUBDIVISION", "Subdivision selection");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERTER_SUBDIVISION_NEW_KEYWORD", "New forum keyword");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERTER_SUBDIVISION_NEW_NAME", "New forum name");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERTER_DIALOG", "Dialog");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_OK", "All messages converted.");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_ERROR", "Conversion error.");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_DATA_ERROR", "Invalid input, try again.");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_NO_CATALOGUE_ERROR", "Catalogue not found.");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_NO_SUBDIVISION", "Subdivision not found.");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_NO_DATA", "Messages missing.");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_NO_PARENT_DATA", "Forum not found.");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_CAN_NOT_CREATE_PARENT", "Forum creation error.");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_NO_GROUPS_DATA", "Forum groups not found.");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_NO_FORUMS_DATA", "Forums not found.");

define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_SETTINGS", "Permissions settings");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_SET_FORUM", "convert forums permissions");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_SET_GROUPS", "converts user groups permissions");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_GROUP_USERS", "Users group");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_GROUP_MODERATORS", "Moderators group");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_VIEW", "view");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_COMMENT", "comment");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_ADD", "add");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_EDIT", "edit");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_CHECK", "check");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_DELETE", "delete");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_SUBSCRIBE", "subscribe");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_MODERATE", "moderate");
define("NETCAT_MODULE_FORUM2_ADMIN_CONVERT_PERMISSION_ADMINISTER", "administer");

define("NETCAT_MODULE_FORUM2_CLASS_UNRECOGNIZED_OBJECT_CALLING", "Unrecognized object call");
define("NETCAT_MODULE_FORUM2_CLASS_UNCORRECT_DATA_FORMAT", "Incorrect data format");
?>