<?php

/* $Id: en.lang.php 6265 2012-02-21 13:53:01Z nastya $ */

define("NC_OPENSTAT_COUNTER", "<!--OPENSTAT_COUNTER-->");
define("NETCAT_MODULE_STATS_DESCRIPTION", "Reports about site visitors.");

define("NETCAT_MODULE_STATS_TYPE_MAIN", "Main statistic");
define("NETCAT_MODULE_STATS_TYPE_GUESTS", "Attendance");
define("NETCAT_MODULE_STATS_TYPE_PAGES", "Popular pages");
define("NETCAT_MODULE_STATS_TYPE_EXTPAGES", "Referal pages");
define("NETCAT_MODULE_STATS_TYPE_USERAGENTS", "Browsers");
define("NETCAT_MODULE_STATS_TYPE_OS", "Operating systems");
define("NETCAT_MODULE_STATS_TYPE_IP", "IP");
define("NETCAT_MODULE_STATS_TYPE_GEO", "Geography");
define("NETCAT_MODULE_STATS_TYPE_PHRASES", "Search queries");

define("NETCAT_MODULE_STATS_TXT_PERIOD", "begin period");
define("NETCAT_MODULE_STATS_TXT_OVER", "to");
define("NETCAT_MODULE_STATS_BUT_SHOW", "Show");

define("NETCAT_MODULE_STATS_PERIOD_TODAY", "today");
define("NETCAT_MODULE_STATS_PERIOD_YESTERDAY", "yesterday");
define("NETCAT_MODULE_STATS_PERIOD_WEEK", "week");
define("NETCAT_MODULE_STATS_PERIOD_MONTHS", "months");
define("NETCAT_MODULE_STATS_PERIOD_TOTAL", "total");
define("NETCAT_MODULE_STATS_PERIOD_ALL", "all period");

define("NETCAT_MODULE_STATS_HOUR", "Hour");
define("NETCAT_MODULE_STATS_HOSTS", "Hosts");
define("NETCAT_MODULE_STATS_HITS", "Hits");
define("NETCAT_MODULE_STATS_USERS", "Users");
define("NETCAT_MODULE_STATS_COUNTRY", "Country");

define("NETCAT_MODULE_STATS_BROWSER", "Browser");
define("NETCAT_MODULE_STATS_PERCENTINGROUP", "Percent in group");
define("NETCAT_MODULE_STATS_TXT_TIPONE", "Number in brakets get view about how many NEW hosts/users load site for last hour.");
define("NETCAT_MODULE_STATS_PAGE", "Page");
define("NETCAT_MODULE_STATS_TXT_TIPTWO", "Avegrage count of hosts, hints and users per period");
define("NETCAT_MODULE_STATS_OS", "Operation system");
define("NETCAT_MODULE_STATS_IP", "IP-address");
define("NETCAT_MODULE_STATS_PHRASE", "Query");

define("NETCAT_MODULE_STATS_NOT_DEFINED", "not defined");
define("NETCAT_MODULE_STATS_CLEAN", "Clear reports before date:");
define("NETCAT_MODULE_STATS_CLEAN_BUTTON", "Clear");
define("NETCAT_MODULE_STATS_CLEAN_SUCCESS", "Reports is successfully cleared.");
define("NETCAT_MODULE_STATS_SHOW_BUTTON", "Show statistics for a site");

define("NETCAT_MODULE_STATS_TXT_HOSTSPERPERIOD", "Hosts, hints and users per period");

define("NETCAT_MODULE_STATS_UNKNOWN", "Unknown");
define("NETCAT_MODULE_STATS_PIE_OTHER", "Other");



define("NETCAT_MODULE_STATS_AD", "ANDORRA");
define("NETCAT_MODULE_STATS_AE", "UNITED ARAB EMIRATES");
define("NETCAT_MODULE_STATS_AF", "AFGHANISTAN");
define("NETCAT_MODULE_STATS_AG", "ANTIGUA AND BARBUDA");
define("NETCAT_MODULE_STATS_AL", "ALBANIA");
define("NETCAT_MODULE_STATS_AM", "ARMENIA");
define("NETCAT_MODULE_STATS_AN", "NETHERLANDS ANTILLES");
define("NETCAT_MODULE_STATS_AO", "ANGOLA");
define("NETCAT_MODULE_STATS_AQ", "ANTARCTICA");
define("NETCAT_MODULE_STATS_AR", "ARGENTINA");
define("NETCAT_MODULE_STATS_AS", "AMERICAN SAMOA");
define("NETCAT_MODULE_STATS_AT", "AUSTRIA");
define("NETCAT_MODULE_STATS_AU", "AUSTRALIA");
define("NETCAT_MODULE_STATS_AW", "ARUBA");
define("NETCAT_MODULE_STATS_AZ", "AZERBAIJAN");
define("NETCAT_MODULE_STATS_BA", "BOSNIA AND HERZEGOVINA");
define("NETCAT_MODULE_STATS_BB", "BARBADOS");
define("NETCAT_MODULE_STATS_BD", "BANGLADESH");
define("NETCAT_MODULE_STATS_BE", "BELGIUM");
define("NETCAT_MODULE_STATS_BG", "BULGARIA");
define("NETCAT_MODULE_STATS_BH", "BAHRAIN");
define("NETCAT_MODULE_STATS_BI", "BURUNDI");
define("NETCAT_MODULE_STATS_BJ", "BENIN");
define("NETCAT_MODULE_STATS_BM", "BERMUDA");
define("NETCAT_MODULE_STATS_BN", "BRUNEI DARUSSALAM");
define("NETCAT_MODULE_STATS_BO", "BOLIVIA");
define("NETCAT_MODULE_STATS_BR", "BRAZIL");
define("NETCAT_MODULE_STATS_BS", "BAHAMAS");
define("NETCAT_MODULE_STATS_BT", "BHUTAN");
define("NETCAT_MODULE_STATS_BW", "BOTSWANA");
define("NETCAT_MODULE_STATS_BY", "BELARUS");
define("NETCAT_MODULE_STATS_BZ", "BELIZE");
define("NETCAT_MODULE_STATS_CA", "CANADA");
define("NETCAT_MODULE_STATS_CD", "THE DEMOCRATIC REPUBLIC OF THE CONGO");
define("NETCAT_MODULE_STATS_CF", "CENTRAL AFRICAN REPUBLIC");
define("NETCAT_MODULE_STATS_CG", "CONGO");
define("NETCAT_MODULE_STATS_CH", "SWITZERLAND");
define("NETCAT_MODULE_STATS_CI", "COTE DIVOIRE");
define("NETCAT_MODULE_STATS_CK", "COOK ISLANDS");
define("NETCAT_MODULE_STATS_CL", "CHILE");
define("NETCAT_MODULE_STATS_CM", "CAMEROON");
define("NETCAT_MODULE_STATS_CN", "CHINA");
define("NETCAT_MODULE_STATS_CO", "COLOMBIA");
define("NETCAT_MODULE_STATS_CR", "COSTA RICA");
define("NETCAT_MODULE_STATS_CS", "SERBIA AND MONTENEGRO");
define("NETCAT_MODULE_STATS_CU", "CUBA");
define("NETCAT_MODULE_STATS_CV", "CAPE VERDE");
define("NETCAT_MODULE_STATS_CY", "CYPRUS");
define("NETCAT_MODULE_STATS_CZ", "CZECH REPUBLIC");
define("NETCAT_MODULE_STATS_DE", "GERMANY");
define("NETCAT_MODULE_STATS_DJ", "DJIBOUTI");
define("NETCAT_MODULE_STATS_DK", "DENMARK");
define("NETCAT_MODULE_STATS_DM", "DOMINICA");
define("NETCAT_MODULE_STATS_DO", "DOMINICAN REPUBLIC");
define("NETCAT_MODULE_STATS_DZ", "ALGERIA");
define("NETCAT_MODULE_STATS_EC", "ECUADOR");
define("NETCAT_MODULE_STATS_EE", "ESTONIA");
define("NETCAT_MODULE_STATS_EG", "EGYPT");
define("NETCAT_MODULE_STATS_ER", "ERITREA");
define("NETCAT_MODULE_STATS_ES", "SPAIN");
define("NETCAT_MODULE_STATS_ET", "ETHIOPIA");
define("NETCAT_MODULE_STATS_FI", "FINLAND");
define("NETCAT_MODULE_STATS_FJ", "FIJI");
define("NETCAT_MODULE_STATS_FK", "FALKLAND ISLANDS (MALVINAS)");
define("NETCAT_MODULE_STATS_FM", "FEDERATED STATES OF MICRONESIA");
define("NETCAT_MODULE_STATS_FO", "FAROE ISLANDS");
define("NETCAT_MODULE_STATS_FR", "FRANCE");
define("NETCAT_MODULE_STATS_GA", "GABON");
define("NETCAT_MODULE_STATS_GB", "UNITED KINGDOM");
define("NETCAT_MODULE_STATS_GD", "GRENADA");
define("NETCAT_MODULE_STATS_GE", "GEORGIA");
define("NETCAT_MODULE_STATS_GF", "FRENCH GUIANA");
define("NETCAT_MODULE_STATS_GH", "GHANA");
define("NETCAT_MODULE_STATS_GI", "GIBRALTAR");
define("NETCAT_MODULE_STATS_GL", "GREENLAND");
define("NETCAT_MODULE_STATS_GM", "GAMBIA");
define("NETCAT_MODULE_STATS_GN", "GUINEA");
define("NETCAT_MODULE_STATS_GP", "GUADELOUPE");
define("NETCAT_MODULE_STATS_GQ", "EQUATORIAL GUINEA");
define("NETCAT_MODULE_STATS_GR", "GREECE");
define("NETCAT_MODULE_STATS_GT", "GUATEMALA");
define("NETCAT_MODULE_STATS_GU", "GUAM");
define("NETCAT_MODULE_STATS_GW", "GUINEA-BISSAU");
define("NETCAT_MODULE_STATS_GY", "GUYANA");
define("NETCAT_MODULE_STATS_HK", "HONG KONG");
define("NETCAT_MODULE_STATS_HN", "HONDURAS");
define("NETCAT_MODULE_STATS_HR", "CROATIA");
define("NETCAT_MODULE_STATS_HT", "HAITI");
define("NETCAT_MODULE_STATS_HU", "HUNGARY");
define("NETCAT_MODULE_STATS_ID", "INDONESIA");
define("NETCAT_MODULE_STATS_IE", "IRELAND");
define("NETCAT_MODULE_STATS_IL", "ISRAEL");
define("NETCAT_MODULE_STATS_IN", "INDIA");
define("NETCAT_MODULE_STATS_IO", "BRITISH INDIAN OCEAN TERRITORY");
define("NETCAT_MODULE_STATS_IQ", "IRAQ");
define("NETCAT_MODULE_STATS_IR", "ISLAMIC REPUBLIC OF IRAN");
define("NETCAT_MODULE_STATS_IS", "ICELAND");
define("NETCAT_MODULE_STATS_IT", "ITALY");
define("NETCAT_MODULE_STATS_JM", "JAMAICA");
define("NETCAT_MODULE_STATS_JO", "JORDAN");
define("NETCAT_MODULE_STATS_JP", "JAPAN");
define("NETCAT_MODULE_STATS_KE", "KENYA");
define("NETCAT_MODULE_STATS_KG", "KYRGYZSTAN");
define("NETCAT_MODULE_STATS_KH", "CAMBODIA");
define("NETCAT_MODULE_STATS_KI", "KIRIBATI");
define("NETCAT_MODULE_STATS_KM", "COMOROS");
define("NETCAT_MODULE_STATS_KN", "SAINT KITTS AND NEVIS");
define("NETCAT_MODULE_STATS_KR", "REPUBLIC OF KOREA");
define("NETCAT_MODULE_STATS_KW", "KUWAIT");
define("NETCAT_MODULE_STATS_KY", "CAYMAN ISLANDS");
define("NETCAT_MODULE_STATS_KZ", "KAZAKHSTAN");
define("NETCAT_MODULE_STATS_LA", "LAO PEOPLES DEMOCRATIC REPUBLIC");
define("NETCAT_MODULE_STATS_LB", "LEBANON");
define("NETCAT_MODULE_STATS_LC", "SAINT LUCIA");
define("NETCAT_MODULE_STATS_LI", "LIECHTENSTEIN");
define("NETCAT_MODULE_STATS_LK", "SRI LANKA");
define("NETCAT_MODULE_STATS_LR", "LIBERIA");
define("NETCAT_MODULE_STATS_LS", "LESOTHO");
define("NETCAT_MODULE_STATS_LT", "LITHUANIA");
define("NETCAT_MODULE_STATS_LU", "LUXEMBOURG");
define("NETCAT_MODULE_STATS_LV", "LATVIA");
define("NETCAT_MODULE_STATS_LY", "LIBYAN ARAB JAMAHIRIYA");
define("NETCAT_MODULE_STATS_MA", "MOROCCO");
define("NETCAT_MODULE_STATS_MC", "MONACO");
define("NETCAT_MODULE_STATS_MD", "REPUBLIC OF MOLDOVA");
define("NETCAT_MODULE_STATS_MG", "MADAGASCAR");
define("NETCAT_MODULE_STATS_MH", "MARSHALL ISLANDS");
define("NETCAT_MODULE_STATS_MK", "THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA");
define("NETCAT_MODULE_STATS_ML", "MALI");
define("NETCAT_MODULE_STATS_MM", "MYANMAR");
define("NETCAT_MODULE_STATS_MN", "MONGOLIA");
define("NETCAT_MODULE_STATS_MO", "MACAO");
define("NETCAT_MODULE_STATS_MP", "NORTHERN MARIANA ISLANDS");
define("NETCAT_MODULE_STATS_MQ", "MARTINIQUE");
define("NETCAT_MODULE_STATS_MR", "MAURITANIA");
define("NETCAT_MODULE_STATS_MT", "MALTA");
define("NETCAT_MODULE_STATS_MU", "MAURITIUS");
define("NETCAT_MODULE_STATS_MV", "MALDIVES");
define("NETCAT_MODULE_STATS_MW", "MALAWI");
define("NETCAT_MODULE_STATS_MX", "MEXICO");
define("NETCAT_MODULE_STATS_MY", "MALAYSIA");
define("NETCAT_MODULE_STATS_MZ", "MOZAMBIQUE");
define("NETCAT_MODULE_STATS_NA", "NAMIBIA");
define("NETCAT_MODULE_STATS_NC", "NEW CALEDONIA");
define("NETCAT_MODULE_STATS_NE", "NIGER");
define("NETCAT_MODULE_STATS_NF", "NORFOLK ISLAND");
define("NETCAT_MODULE_STATS_NG", "NIGERIA");
define("NETCAT_MODULE_STATS_NI", "NICARAGUA");
define("NETCAT_MODULE_STATS_NL", "NETHERLANDS");
define("NETCAT_MODULE_STATS_NO", "NORWAY");
define("NETCAT_MODULE_STATS_NP", "NEPAL");
define("NETCAT_MODULE_STATS_NR", "NAURU");
define("NETCAT_MODULE_STATS_NZ", "NEW ZEALAND");
define("NETCAT_MODULE_STATS_OM", "OMAN");
define("NETCAT_MODULE_STATS_PA", "PANAMA");
define("NETCAT_MODULE_STATS_PE", "PERU");
define("NETCAT_MODULE_STATS_PF", "FRENCH POLYNESIA");
define("NETCAT_MODULE_STATS_PG", "PAPUA NEW GUINEA");
define("NETCAT_MODULE_STATS_PH", "PHILIPPINES");
define("NETCAT_MODULE_STATS_PK", "PAKISTAN");
define("NETCAT_MODULE_STATS_PL", "POLAND");
define("NETCAT_MODULE_STATS_PR", "PUERTO RICO");
define("NETCAT_MODULE_STATS_PS", "PALESTINIAN TERRITORY, OCCUPIED");
define("NETCAT_MODULE_STATS_PT", "PORTUGAL");
define("NETCAT_MODULE_STATS_PW", "PALAU");
define("NETCAT_MODULE_STATS_PY", "PARAGUAY");
define("NETCAT_MODULE_STATS_QA", "QATAR");
define("NETCAT_MODULE_STATS_RE", "REUNION");
define("NETCAT_MODULE_STATS_RO", "ROMANIA");
define("NETCAT_MODULE_STATS_RU", "RUSSIAN FEDERATION");
define("NETCAT_MODULE_STATS_RW", "RWANDA");
define("NETCAT_MODULE_STATS_SA", "SAUDI ARABIA");
define("NETCAT_MODULE_STATS_SB", "SOLOMON ISLANDS");
define("NETCAT_MODULE_STATS_SC", "SEYCHELLES");
define("NETCAT_MODULE_STATS_SD", "SUDAN");
define("NETCAT_MODULE_STATS_SE", "SWEDEN");
define("NETCAT_MODULE_STATS_SG", "SINGAPORE");
define("NETCAT_MODULE_STATS_SI", "SLOVENIA");
define("NETCAT_MODULE_STATS_SK", "SLOVAKIA");
define("NETCAT_MODULE_STATS_SL", "SIERRA LEONE");
define("NETCAT_MODULE_STATS_SM", "SAN MARINO");
define("NETCAT_MODULE_STATS_SN", "SENEGAL");
define("NETCAT_MODULE_STATS_SO", "SOMALIA");
define("NETCAT_MODULE_STATS_SR", "SURINAME");
define("NETCAT_MODULE_STATS_ST", "SAO TOME AND PRINCIPE");
define("NETCAT_MODULE_STATS_SV", "EL SALVADOR");
define("NETCAT_MODULE_STATS_SY", "SYRIAN ARAB REPUBLIC");
define("NETCAT_MODULE_STATS_SZ", "SWAZILAND");
define("NETCAT_MODULE_STATS_TD", "CHAD");
define("NETCAT_MODULE_STATS_TF", "FRENCH SOUTHERN TERRITORIES");
define("NETCAT_MODULE_STATS_TG", "TOGO");
define("NETCAT_MODULE_STATS_TH", "THAILAND");
define("NETCAT_MODULE_STATS_TJ", "TAJIKISTAN");
define("NETCAT_MODULE_STATS_TK", "TOKELAU");
define("NETCAT_MODULE_STATS_TL", "TIMOR-LESTE");
define("NETCAT_MODULE_STATS_TM", "TURKMENISTAN");
define("NETCAT_MODULE_STATS_TN", "TUNISIA");
define("NETCAT_MODULE_STATS_TO", "TONGA");
define("NETCAT_MODULE_STATS_TR", "TURKEY");
define("NETCAT_MODULE_STATS_TT", "TRINIDAD AND TOBAGO");
define("NETCAT_MODULE_STATS_TV", "TUVALU");
define("NETCAT_MODULE_STATS_TW", "TAIWAN");
define("NETCAT_MODULE_STATS_TZ", "UNITED REPUBLIC OF TANZANIA");
define("NETCAT_MODULE_STATS_UA", "UKRAINE");
define("NETCAT_MODULE_STATS_UG", "UGANDA");
define("NETCAT_MODULE_STATS_US", "UNITED STATES");
define("NETCAT_MODULE_STATS_UY", "URUGUAY");
define("NETCAT_MODULE_STATS_UZ", "UZBEKISTAN");
define("NETCAT_MODULE_STATS_VA", "HOLY SEE (VATICAN CITY STATE)");
define("NETCAT_MODULE_STATS_VC", "SAINT VINCENT AND THE GRENADINES");
define("NETCAT_MODULE_STATS_VE", "VENEZUELA");
define("NETCAT_MODULE_STATS_VG", "VIRGIN ISLANDS, BRITISH");
define("NETCAT_MODULE_STATS_VI", "VIRGIN ISLANDS, U.S.");
define("NETCAT_MODULE_STATS_VN", "VIET NAM");
define("NETCAT_MODULE_STATS_VU", "VANUATU");
define("NETCAT_MODULE_STATS_WS", "SAMOA");
define("NETCAT_MODULE_STATS_YE", "YEMEN");
define("NETCAT_MODULE_STATS_YT", "MAYOTTE");
define("NETCAT_MODULE_STATS_ZA", "SOUTH AFRICA");
define("NETCAT_MODULE_STATS_ZM", "ZAMBIA");
define("NETCAT_MODULE_STATS_ZW", "ZIMBABWE");
define("NETCAT_MODULE_STATS_YU", "YUGOSLAVIA");
define("NETCAT_MODULE_STATS_EU", "EUROPEAN UNION");


define("NETCAT_MODULE_STATS_SAVE_CHANGES", "Save changes");
define("NETCAT_MODULE_STATS_CHANGES_SAVED", "Changes have been saved");
define("NETCAT_MODULE_STATS_OPENSTAT_API_COUNTER_CREATED", "The counter is created, and from that moment he begins to gather statistics on your site.<br />\nReports can be found <a href='admin.php?sub_view=reports&phase=%PASE_ID'>here</a>.");
define("NETCAT_MODULE_STATS_OPENSTAT_USER_COUNTER_CREATED", "The counter is created, and from that moment he begins to gather statistics on your site.<br />\nReports can be found on <a href='http://www.openstat.ru/' target='_blank'>Openstat</a> web-site.");

define("NETCAT_MODULE_STATS_ADMIN_TAB_NC_STAT", "NetCat statistics");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT", "Openstat statistics");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_REPORT", "Reports");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_COUNTERS", "Counters");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_TEMPLATES", "Templates");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_TOOLS", "Settings");

define("NETCAT_MODULE_STATS_ADMIN_TAB_ANALYTICS", "External analytics");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_ENABLE", "Add Google Analytics, Yandex.Metrika and NetCat integration script on all site pages");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_ECOMMERCE_ENABLE", "Register E-Commerce events");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_SCRIPT_POSITION", "Scripts insertion point");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_SCRIPT_POSITION_BODY_TOP", "at the beginning of <body>");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_SCRIPT_POSITION_BODY_BOTTOM", "at the end of <body>");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_GA_CODE", "Google Universal Analytics tracking code or Google Tag Manager code");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_YM_CODE", "Yandex.Metrika counter code");

define("NETCAT_MODULE_STATS_ENABLE", "Enable NetCat statistics");
define("NETCAT_MODULE_STATS_OPENSTAT_ENABLE", "Enable Openstat statistics");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_DISABLED", "Openstat statistics is disabled now. <a href=\"../settings.php?openstat_enable=1\">Enable</a>");
define("NETCAT_MODULE_STATS_ADMIN_TAB_NC_STAT_DISABLED", "NetCat statistics is disabled now. <a href=\"settings.php?nc_stat_enable=1\">Enable</a>");

define("NETCAT_MODULE_STATS_OPENSTAT_NO_COUNTERS", "There is no counter!");
define("NETCAT_MODULE_STATS_OPENSTAT_NO_COUNTER_IN_CATALOGUE", "There is no counter for this site.");
define("NETCAT_MODULE_STATS_OPENSTAT_NO_COUNTERS_IN_TEMPL", "There is no counter code in sone templates!<br />Insert ".htmlspecialchars(NC_OPENSTAT_COUNTER)." in all templates manually or click \"<a href=\"?sub_view=templates&DoAction=1&phase=2\">Insert counter code in all templates</a>\".");

define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_CATALOGUE", "Site");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_DELETE", "Delete");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_EDIT", "Edit");
define("NETCAT_MODULE_STATS_OPENSTAT_BACK", "Back");
define("NETCAT_MODULE_STATS_OPENSTAT_INSERT_COUNTER", "Insert counter");
define("NETCAT_MODULE_STATS_OPENSTAT_ADD_COUNTER", "Create counter");
define("NETCAT_MODULE_STATS_OPENSTAT_ADD_USER_COUNTER", "I've already had Openstat counter");
define("NETCAT_MODULE_STATS_OPENSTAT_ADD_API_COUNTER", "I want to create a new Openstat counter");
define("NETCAT_MODULE_STATS_OPENSTAT_TEMPLATE", "Template");
define("NETCAT_MODULE_STATS_OPENSTAT_INS_IN_ALL_TEMPLATES", "Insert counter in all templates");
define("NETCAT_MODULE_STATS_OPENSTAT_DEL_FROM_ALL_TEMPLATES", "Delete counter from all templates");

define("NETCAT_MODULE_STATS_OPENSTAT_DEL_SELECTED", "Delete selected");
define("NETCAT_MODULE_STATS_OPENSTAT_DEL_ALL", "Delete all");
define("NETCAT_MODULE_STATS_OPENSTAT_DEL_ALL_CONFIRM", "Are you sure you want to permanently delete all the counters?");
define("NETCAT_MODULE_STATS_OPENSTAT_DEL_SELECTED_CONFIRM", "Are you sure you want to permanently delete the selected counters?");

define("NETCAT_MODULE_STATS_OPENSTAT_YES", "Yes");
define("NETCAT_MODULE_STATS_OPENSTAT_NO", "No");

define("NETCAT_MODULE_STATS_OPENSTAT_RULES", "I accept the <a target='_blank' href='https://www.openstat.ru/service/legal/privacy-policy'> Privacy Policy </ a> and I agree with <a target = '_blank' href = 'https://www.openstat.ru/legal/rules'> Rules of using the service </ a>, set out on the web site Openstat");
define("NETCAT_MODULE_STATS_OPENSTAT_ALL_SITES", "All sites");
define("NETCAT_MODULE_STATS_OPENSTAT_COMMON_SETTINGS", "Common settings");
define("NETCAT_MODULE_STATS_OPENSTAT_DISPLAY_SETTINGS", "Appearance");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR", "Counter color");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_0", "\"Transparent pixel\"(picture is not shown)");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_1", "Light gray");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_2", "Dark gray");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_3", "Black");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_4", "Blue");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_5", "Light-blue");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_6", "Dark green");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_7", "Green");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_8", "Yellow");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_9", "Orange");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_10", "Red");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_11", "Pink");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_12", "Vinous");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_13", "Violet");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_COUNT", "14");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE", "Image type of the counter (makes sense only if the color does not \"transparent pixel\"");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_1", "Image 88x31 pixel, without indicator");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_2", "Image 88х31 pixel, with indicator");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_3", "Image 88х15 pixel, with indicator");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_4", "Image 31х31 pixel, without indicator, light gray background");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_5", "Image 31х31 pixel, without indicator, transparent background");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_COUNT", "5");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS", "Tracking links");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS_NONE", "None");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS_ALL", "All");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS_EXT", "External only");
define("NETCAT_MODULE_STATS_OPENSTAT_OTHER_SETTINGS", "Other settings");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COUNTER_RATING", "I would like to participate in the ratings of sites Openstat.");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COUNTER_ADVERT", "The site is advertising platform");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_INSERT_IN_ALL_TEMPLATES_RECOMMENDED", "Insert the counter code in all templates(recommended)");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_CODE", "Counter code");

define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NO_USER_COUNTER_CODE", "You have not entered the counter code.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_LICENSE_NOT_AGREE", "You have not confirmed their acceptance of the rules. Using the counters Openstat impossible.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NO_PRODUCT_NUMBER", "With the system you did not enter the activation key. Please contact support.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_INVALID_PRODUCT_NUMBER", "With the system you entered the wrong license number or activation key. Please contact support.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NO_CONN_WITH_NETCAT", "Unsuccessful attempt to connect to the server NetCat. Check the settings for DNS-client or try to create a counter later. Error Code: ");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_USER_ALREADY_REGISTERED", "For the license has already been registered user on Openstat. Please contact support.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NEW_USER_UNKNOWN_ERROR", "There was an error while registering user on Openstat. Please contact technical support. Error Code:");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NEW_COUNTER_UNKNOWN_ERROR", "Error creating counter. Please contact technical support. Error Code: ");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_EDIT_COUNTER_UNKNOWN_ERROR", "Error when changing the counter parameters. Please contact technical support. Error Code: ");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_COUNTER_AUTH_ERROR", "Invalid user credentials Openstat. Please contact technical support.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NEW_CODE_UNKNOWN_ERROR", "Failed to get the counter code. Please contact technical support. Error Code: ");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_INVALID_OPENSTAT_COUNTER_ID", "Counter with such ID is not registered on Openstat. Please contact technical support.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_ALREADY_COUNTERS_FOR_ALL_SITES", "You have already set up counters for all sites.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_DEL_COUNTER", "Error while removing the counter. Please contact technical support. Error Code: ");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_COUNTER_REPORT", "Failure to get the report. Please contact technical support. Error Code: ");
define("NETCAT_MODULE_STATS_DB_INSERT_ERR", "Failed to add data into the database");

define("NETCAT_MODULE_STATS_OPENSTAT_INVALID_COUNTER_ID", "Counter with this ID does not exist!");

define("NETCAT_MODULE_STATS_OPENSTAT_SELECT_COUNTER", "Select counter");

define("NETCAT_MODULE_STATS_OPENSTAT_SEE_STATS_ON_OPENSTAT", "See statistics on the site");
define("NETCAT_MODULE_STATS_OPENSTAT_SEE_FULL_STATS_ON_OPENSTAT", "See detailed statistics on the site");

define("NETCAT_MODULE_STATS_OPENSTAT_VISITORS", "Visitors");
define("NETCAT_MODULE_STATS_OPENSTAT_SESSIONS", "Sessions");
define("NETCAT_MODULE_STATS_OPENSTAT_PAGEVIEWS", "Page views");
define("NETCAT_MODULE_STATS_OPENSTAT_TRANSITIONS", "Transitions");
define("NETCAT_MODULE_STATS_OPENSTAT_PAGE", "Page");
define("NETCAT_MODULE_STATS_OPENSTAT_TYPE", "Type");
define("NETCAT_MODULE_STATS_OPENSTAT_PHRASE", "Phrase");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTRY", "Country");
define("NETCAT_MODULE_STATS_OPENSTAT_REGION", "Region");


define("NETCAT_MODULE_STATS_OPENSTAT_TOP_5", "top-5");
define("NETCAT_MODULE_STATS_OPENSTAT_SEC", "sec.");
define("NETCAT_MODULE_STATS_OPENSTAT_MIN", "min.");
define("NETCAT_MODULE_STATS_OPENSTAT_MORE", "more");

define("NETCAT_MODULE_STATS_OPENSTAT_INVALID_START_DATE", "The start date of the report is incorrect.");
define("NETCAT_MODULE_STATS_OPENSTAT_INVALID_END_DATE", "The end date of the report is incorrect.");
define("NETCAT_MODULE_STATS_OPENSTAT_INVALID_PERIOD", "Too much period for such detail.");
define("NETCAT_MODULE_STATS_OPENSTAT_START_DATE_TOO_BIG", "The start date must be less than the end date.");

define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_1", "JAN");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_2", "FEB");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_3", "MAR");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_4", "APR");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_5", "MAY");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_6", "JUN");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_7", "JUL");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_8", "AUG");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_9", "SEP");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_10", "OCT");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_11", "NOV");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_12", "DEC");


define("NETCAT_MODULE_STATS_OPENSTAT_LAST_MONTH", "month");
define("NETCAT_MODULE_STATS_OPENSTAT_LAST_WEEK", "week");
define("NETCAT_MODULE_STATS_OPENSTAT_YESTERDAY", "yesterday");

define("NETCAT_MODULE_STATS_OPENSTAT_SUMMARY_STATS", "Summary statistics");
define("NETCAT_MODULE_STATS_OPENSTAT_SUM_VISITORS", "Total visitors");
define("NETCAT_MODULE_STATS_OPENSTAT_SUM_SESSIONS", "Total sessions");
define("NETCAT_MODULE_STATS_OPENSTAT_SUM_PAGEVIEWS", "Total page views");
define("NETCAT_MODULE_STATS_OPENSTAT_FAILURES_NUM", "Failures percent");
define("NETCAT_MODULE_STATS_OPENSTAT_AVERAGE_PAGEVIEWS_PER_SESSION", "Average page views per session");
define("NETCAT_MODULE_STATS_OPENSTAT_AVERAGE_TIME_SITE", "Average time on site");

define("NETCAT_MODULE_STATS_OPENSTAT_PAGES", "Pages");
define("NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_SOURCES", "Trafic sources");
define("NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_GEOGRAPY", "Internet-users geography");
define("NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_GEOGRAPY_BY_COUNTRIES", "Geography by countries");
define("NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_GEOGRAPY_BY_REGIONS", "Geography by regions");

define("NETCAT_MODULE_STATS_OPENSTAT_NO_DATA", "no data");

define("NETCAT_MODULE_STATS_OPENSTAT_REDIRECTING_TO", "Redirecting to");
define("NETCAT_MODULE_STATS_OPENSTAT_WAIT_OR_CLICK", "Wait for automatic redirecting or click");
define("NETCAT_MODULE_STATS_OPENSTAT_GO", "Go");

define("NETCAT_MODULE_STATS_OPENSTAT_NOT_FOUND_CURL", "Extension cURL not found");

// выкинуть!
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_PERIOD", "Statistics by");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_HOUR", "hour");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_DAY", "day");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_WEEK", "week");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_MONTH", "month");

define("NETCAT_MODULE_STATS_OPENSTAT_STATS_FROM", "from");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_TILL", "till");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_SHOW", "Show");
?>