<?php

/* $Id: ru_utf8.lang.php 4290 2011-02-23 15:32:35Z denis $ */

define("NC_OPENSTAT_COUNTER", "<!--OPENSTAT_COUNTER-->");
define("NETCAT_MODULE_STATS_DESCRIPTION", "Отчеты о статистике посещений на сайте.");

define("NETCAT_MODULE_STATS_TYPE_MAIN", "Сводная статистика");
define("NETCAT_MODULE_STATS_TYPE_GUESTS", "Посещаемость");
define("NETCAT_MODULE_STATS_TYPE_PAGES", "Популярность страниц");
define("NETCAT_MODULE_STATS_TYPE_EXTPAGES", "Ссылающиеся страницы");
define("NETCAT_MODULE_STATS_TYPE_USERAGENTS", "Браузеры");
define("NETCAT_MODULE_STATS_TYPE_OS", "Операционные системы");
define("NETCAT_MODULE_STATS_TYPE_IP", "IP-адреса");
define("NETCAT_MODULE_STATS_TYPE_GEO", "География");
define("NETCAT_MODULE_STATS_TYPE_PHRASES", "Поисковые фразы");

define("NETCAT_MODULE_STATS_TXT_PERIOD", "за период с");
define("NETCAT_MODULE_STATS_TXT_OVER", "по");
define("NETCAT_MODULE_STATS_BUT_SHOW", "Показать");

define("NETCAT_MODULE_STATS_PERIOD_TODAY", "сегодня");
define("NETCAT_MODULE_STATS_PERIOD_YESTERDAY", "вчера");
define("NETCAT_MODULE_STATS_PERIOD_WEEK", "неделя");
define("NETCAT_MODULE_STATS_PERIOD_PER_WEEK", "в неделю");
define("NETCAT_MODULE_STATS_PERIOD_MONTHS", "месяц");
define("NETCAT_MODULE_STATS_PERIOD_TOTAL", "всего");
define("NETCAT_MODULE_STATS_PERIOD_ALL", "весь период");

define("NETCAT_MODULE_STATS_HOUR", "Час");
define("NETCAT_MODULE_STATS_HOSTS", "Хосты");
define("NETCAT_MODULE_STATS_HITS", "Хиты");
define("NETCAT_MODULE_STATS_USERS", "Посетители");
define("NETCAT_MODULE_STATS_COUNTRY", "Страна");

define("NETCAT_MODULE_STATS_BROWSER", "Браузер");
define("NETCAT_MODULE_STATS_PERCENTINGROUP", "Процент в группе");
define("NETCAT_MODULE_STATS_TXT_TIPONE", "В скобках указано, сколько новых хостов/посетителей пришло на сайт в течение часа.");
define("NETCAT_MODULE_STATS_PAGE", "Страница");
define("NETCAT_MODULE_STATS_TXT_TIPTWO", "Среднее число хостов, хитов и посетителей за указанный период");
define("NETCAT_MODULE_STATS_OS", "Операционная система");
define("NETCAT_MODULE_STATS_IP", "IP-адрес");
define("NETCAT_MODULE_STATS_PHRASE", "Фраза");

define("NETCAT_MODULE_STATS_NOT_DEFINED", "не определено");
define("NETCAT_MODULE_STATS_CLEAN", "Очистить статистику до даты:");
define("NETCAT_MODULE_STATS_CLEAN_BUTTON", "Очистить");
define("NETCAT_MODULE_STATS_CLEAN_SUCCESS", "Статистика успешно очищена.");
define("NETCAT_MODULE_STATS_SHOW_BUTTON", "Показать статистику по выбранному сайту");

define("NETCAT_MODULE_STATS_TXT_HOSTSPERPERIOD", "Количество хостов, хитов и посетителей за указанный период");

define("NETCAT_MODULE_STATS_UNKNOWN", "Неизвестно");
define("NETCAT_MODULE_STATS_PIE_OTHER", "Прочие");



define("NETCAT_MODULE_STATS_AD", "АНДОРРА");
define("NETCAT_MODULE_STATS_AE", "Объединенные Арабские Эмираты");
define("NETCAT_MODULE_STATS_AF", "АФГАНИСТАН");
define("NETCAT_MODULE_STATS_AG", "Антигуа и Барбуда");
define("NETCAT_MODULE_STATS_AL", "АЛБАНИЯ");
define("NETCAT_MODULE_STATS_AM", "АРМЕНИЯ");
define("NETCAT_MODULE_STATS_AN", "NETHERLANDS ANTILLES");
define("NETCAT_MODULE_STATS_AO", "АНГОЛА");
define("NETCAT_MODULE_STATS_AQ", "АНТАРКТИКЕ");
define("NETCAT_MODULE_STATS_AR", "АРГЕНТИНА");
define("NETCAT_MODULE_STATS_AS", "АМЕРИКАНСКОЕ САМОА");
define("NETCAT_MODULE_STATS_AT", "АВСТРИЯ");
define("NETCAT_MODULE_STATS_AU", "АВСТРАЛИЯ");
define("NETCAT_MODULE_STATS_AW", "АРУБА");
define("NETCAT_MODULE_STATS_AZ", "АЗЕРБАЙДЖАН");
define("NETCAT_MODULE_STATS_BA", "Босния и Герцеговина");
define("NETCAT_MODULE_STATS_BB", "БАРБАДОС");
define("NETCAT_MODULE_STATS_BD", "БАНГЛАДЕШ");
define("NETCAT_MODULE_STATS_BE", "БЕЛЬГИЯ");
define("NETCAT_MODULE_STATS_BG", "БОЛГАРИЯ");
define("NETCAT_MODULE_STATS_BH", "БАХРЕЙН");
define("NETCAT_MODULE_STATS_BI", "БУРУНДИ");
define("NETCAT_MODULE_STATS_BJ", "БЕНИН");
define("NETCAT_MODULE_STATS_BM", "Бермудские острова");
define("NETCAT_MODULE_STATS_BN", "BRUNEI DARUSSALAM");
define("NETCAT_MODULE_STATS_BO", "БОЛИВИЯ");
define("NETCAT_MODULE_STATS_BR", "БРАЗИЛИЯ");
define("NETCAT_MODULE_STATS_BS", "BAHAMAS");
define("NETCAT_MODULE_STATS_BT", "BHUTAN");
define("NETCAT_MODULE_STATS_BW", "БОТСВАНА");
define("NETCAT_MODULE_STATS_BY", "БЕЛАРУСЬ");
define("NETCAT_MODULE_STATS_BZ", "БЕЛИЗ");
define("NETCAT_MODULE_STATS_CA", "КАНАДА");
define("NETCAT_MODULE_STATS_CD", "ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА КОНГО");
define("NETCAT_MODULE_STATS_CF", "Центральноафриканской Республике");
define("NETCAT_MODULE_STATS_CG", "КОНГО");
define("NETCAT_MODULE_STATS_CH", "ШВЕЙЦАРИЯ");
define("NETCAT_MODULE_STATS_CI", "КОТ DIVOIRE");
define("NETCAT_MODULE_STATS_CK", "COOK ISLANDS");
define("NETCAT_MODULE_STATS_CL", "ЧИЛИ");
define("NETCAT_MODULE_STATS_CM", "КАМЕРУН");
define("NETCAT_MODULE_STATS_CN", "КИТАЙ");
define("NETCAT_MODULE_STATS_CO", "КОЛУМБИЯ");
define("NETCAT_MODULE_STATS_CR", "КОСТА-РИКА");
define("NETCAT_MODULE_STATS_CS", "Сербия и Черногория");
define("NETCAT_MODULE_STATS_CU", "КУБА");
define("NETCAT_MODULE_STATS_CV", "CAPE VERDE");
define("NETCAT_MODULE_STATS_CY", "КИПР");
define("NETCAT_MODULE_STATS_CZ", "ЧЕШСКАЯ РЕСПУБЛИКА");
define("NETCAT_MODULE_STATS_DE", "ГЕРМАНИЯ");
define("NETCAT_MODULE_STATS_DJ", "DJIBOUTI");
define("NETCAT_MODULE_STATS_DK", "ДАНИЯ");
define("NETCAT_MODULE_STATS_DM", "ДОМИНИКА");
define("NETCAT_MODULE_STATS_DO", "ДОМИНИКАНСКАЯ РЕСПУБЛИКА");
define("NETCAT_MODULE_STATS_DZ", "АЛЖИР");
define("NETCAT_MODULE_STATS_EC", "ЭКВАДОР");
define("NETCAT_MODULE_STATS_EE", "ЭСТОНИЯ");
define("NETCAT_MODULE_STATS_EG", "ЕГИПЕТ");
define("NETCAT_MODULE_STATS_ER", "ЭРИТРЕЯ");
define("NETCAT_MODULE_STATS_ES", "ИСПАНИЯ");
define("NETCAT_MODULE_STATS_ET", "ЭФИОПИЯ");
define("NETCAT_MODULE_STATS_FI", "ФИНЛЯНДИЯ");
define("NETCAT_MODULE_STATS_FJ", "ФИДЖИ");
define("NETCAT_MODULE_STATS_FK", "Фолклендских (Мальвинских)");
define("NETCAT_MODULE_STATS_FM", "Федеративные Штаты Микронезии");
define("NETCAT_MODULE_STATS_FO", "FAROE ISLANDS");
define("NETCAT_MODULE_STATS_FR", "ФРАНЦИЯ");
define("NETCAT_MODULE_STATS_GA", "GABON");
define("NETCAT_MODULE_STATS_GB", "ВЕЛИКОБРИТАНИЯ");
define("NETCAT_MODULE_STATS_GD", "GRENADA");
define("NETCAT_MODULE_STATS_GE", "ГРУЗИЯ");
define("NETCAT_MODULE_STATS_GF", "FRENCH GUIANA");
define("NETCAT_MODULE_STATS_GH", "ГАНА");
define("NETCAT_MODULE_STATS_GI", "ГИБРАЛТАР");
define("NETCAT_MODULE_STATS_GL", "ГРЕНЛАНДИЯ");
define("NETCAT_MODULE_STATS_GM", "ГАМБИЯ");
define("NETCAT_MODULE_STATS_GN", "ГВИНЕЯ");
define("NETCAT_MODULE_STATS_GP", "GUADELOUPE");
define("NETCAT_MODULE_STATS_GQ", "EQUATORIAL GUINEA");
define("NETCAT_MODULE_STATS_GR", "ГРЕЦИЯ");
define("NETCAT_MODULE_STATS_GT", "ГВАТЕМАЛА");
define("NETCAT_MODULE_STATS_GU", "ГУАМ");
define("NETCAT_MODULE_STATS_GW", "GUINEA-BISSAU");
define("NETCAT_MODULE_STATS_GY", "ГАЙАНА");
define("NETCAT_MODULE_STATS_HK", "HONG KONG");
define("NETCAT_MODULE_STATS_HN", "HONDURAS");
define("NETCAT_MODULE_STATS_HR", "ХОРВАТИЯ");
define("NETCAT_MODULE_STATS_HT", "ГАИТИ");
define("NETCAT_MODULE_STATS_HU", "ВЕНГРИЯ");
define("NETCAT_MODULE_STATS_ID", "ИНДОНЕЗИЯ");
define("NETCAT_MODULE_STATS_IE", "ИРЛАНДИЯ");
define("NETCAT_MODULE_STATS_IL", "ИЗРАИЛЬ");
define("NETCAT_MODULE_STATS_IN", "ИНДИЯ");
define("NETCAT_MODULE_STATS_IO", "Британская территория в Индийском океане");
define("NETCAT_MODULE_STATS_IQ", "ИРАК");
define("NETCAT_MODULE_STATS_IR", "ИСЛАМСКОЙ РЕСПУБЛИКИ ИРАН");
define("NETCAT_MODULE_STATS_IS", "ИСЛАНДИЯ");
define("NETCAT_MODULE_STATS_IT", "ИТАЛИЯ");
define("NETCAT_MODULE_STATS_JM", "JAMAICA");
define("NETCAT_MODULE_STATS_JO", "JORDAN");
define("NETCAT_MODULE_STATS_JP", "ЯПОНИЯ");
define("NETCAT_MODULE_STATS_KE", "КЕНИЯ");
define("NETCAT_MODULE_STATS_KG", "КЫРГЫЗСТАН");
define("NETCAT_MODULE_STATS_KH", "КАМБОДЖА");
define("NETCAT_MODULE_STATS_KI", "KIRIBATI");
define("NETCAT_MODULE_STATS_KM", "COMOROS");
define("NETCAT_MODULE_STATS_KN", "Сент-Китс и Невис");
define("NETCAT_MODULE_STATS_KR", "Республика Корея");
define("NETCAT_MODULE_STATS_KW", "КУВЕЙТ");
define("NETCAT_MODULE_STATS_KY", "КАЙМАНОВЫ ОСТРОВА");
define("NETCAT_MODULE_STATS_KZ", "КАЗАХСТАН");
define("NETCAT_MODULE_STATS_LA", "Лаосская Народно-Демократическая республика");
define("NETCAT_MODULE_STATS_LB", "ЛИВАН");
define("NETCAT_MODULE_STATS_LC", "SAINT LUCIA");
define("NETCAT_MODULE_STATS_LI", "ЛИХТЕНШТЕЙН");
define("NETCAT_MODULE_STATS_LK", "SRI LANKA");
define("NETCAT_MODULE_STATS_LR", "ЛИБЕРИЯ");
define("NETCAT_MODULE_STATS_LS", "LESOTHO");
define("NETCAT_MODULE_STATS_LT", "ЛИТВА");
define("NETCAT_MODULE_STATS_LU", "ЛЮКСЕМБУРГ");
define("NETCAT_MODULE_STATS_LV", "ЛАТВИЯ");
define("NETCAT_MODULE_STATS_LY", "Ливийская Арабская Джамахирия");
define("NETCAT_MODULE_STATS_MA", "МАРОККО");
define("NETCAT_MODULE_STATS_MC", "МОНАКО");
define("NETCAT_MODULE_STATS_MD", "Республика Молдова");
define("NETCAT_MODULE_STATS_MG", "МАДАГАСКАР");
define("NETCAT_MODULE_STATS_MH", "MARSHALL ISLANDS");
define("NETCAT_MODULE_STATS_MK", "Бывшей югославской Республики Македонии");
define("NETCAT_MODULE_STATS_ML", "МАЛИ");
define("NETCAT_MODULE_STATS_MM", "MYANMAR");
define("NETCAT_MODULE_STATS_MN", "МОНГОЛИЯ");
define("NETCAT_MODULE_STATS_MO", "МАКАО");
define("NETCAT_MODULE_STATS_MP", "Северные Марианские острова");
define("NETCAT_MODULE_STATS_MQ", "MARTINIQUE");
define("NETCAT_MODULE_STATS_MR", "МАВРИТАНИЯ");
define("NETCAT_MODULE_STATS_MT", "МАЛЬТА");
define("NETCAT_MODULE_STATS_MU", "МАВРИКИЙ");
define("NETCAT_MODULE_STATS_MV", "MALDIVES");
define("NETCAT_MODULE_STATS_MW", "MALAWI");
define("NETCAT_MODULE_STATS_MX", "МЕКСИКА");
define("NETCAT_MODULE_STATS_MY", "МАЛАЙЗИЯ");
define("NETCAT_MODULE_STATS_MZ", "МОЗАМБИК");
define("NETCAT_MODULE_STATS_NA", "НАМИБИЯ");
define("NETCAT_MODULE_STATS_NC", "НОВАЯ КАЛЕДОНИЯ");
define("NETCAT_MODULE_STATS_NE", "НИГЕРИЯ");
define("NETCAT_MODULE_STATS_NF", "NORFOLK ISLAND");
define("NETCAT_MODULE_STATS_NG", "НИГЕРИЯ");
define("NETCAT_MODULE_STATS_NI", "НИКАРАГУА");
define("NETCAT_MODULE_STATS_NL", "НИДЕРЛАНДЫ");
define("NETCAT_MODULE_STATS_NO", "НОРВЕГИЯ");
define("NETCAT_MODULE_STATS_NP", "НЕПАЛ");
define("NETCAT_MODULE_STATS_NR", "NAURU");
define("NETCAT_MODULE_STATS_NZ", "НОВАЯ ЗЕЛАНДИЯ");
define("NETCAT_MODULE_STATS_OM", "ОМАН");
define("NETCAT_MODULE_STATS_PA", "ПАНАМА");
define("NETCAT_MODULE_STATS_PE", "ПЕРУ");
define("NETCAT_MODULE_STATS_PF", "FRENCH POLYNESIA");
define("NETCAT_MODULE_STATS_PG", "ПАПУА-НОВАЯ ГВИНЕЯ");
define("NETCAT_MODULE_STATS_PH", "ФИЛИППИНЫ");
define("NETCAT_MODULE_STATS_PK", "ПАКИСТАН");
define("NETCAT_MODULE_STATS_PL", "ПОЛЬША");
define("NETCAT_MODULE_STATS_PR", "ПУЭРТО-РИКО");
define("NETCAT_MODULE_STATS_PS", "Палестинской территории,  оккупированной");
define("NETCAT_MODULE_STATS_PT", "ПОРТУГАЛИЯ");
define("NETCAT_MODULE_STATS_PW", "ПАЛАУ");
define("NETCAT_MODULE_STATS_PY", "ПАРАГВАЙ");
define("NETCAT_MODULE_STATS_QA", "КАТАР");
define("NETCAT_MODULE_STATS_RE", "REUNION");
define("NETCAT_MODULE_STATS_RO", "РУМЫНИЯ");
define("NETCAT_MODULE_STATS_RU", "РОССИЙСКАЯ ФЕДЕРАЦИЯ");
define("NETCAT_MODULE_STATS_RW", "РУАНДА");
define("NETCAT_MODULE_STATS_SA", "САУДОВСКАЯ АРАВИЯ");
define("NETCAT_MODULE_STATS_SB", "СОЛОМОНОВЫ ОСТРОВА");
define("NETCAT_MODULE_STATS_SC", "Сейшельские острова");
define("NETCAT_MODULE_STATS_SD", "СУДАН");
define("NETCAT_MODULE_STATS_SE", "ШВЕЦИЯ");
define("NETCAT_MODULE_STATS_SG", "СИНГАПУР");
define("NETCAT_MODULE_STATS_SI", "СЛОВЕНИЯ");
define("NETCAT_MODULE_STATS_SK", "СЛОВАКИЯ");
define("NETCAT_MODULE_STATS_SL", "СЬЕРРА-ЛЕОНЕ");
define("NETCAT_MODULE_STATS_SM", "САН-МАРИНО");
define("NETCAT_MODULE_STATS_SN", "SENEGAL");
define("NETCAT_MODULE_STATS_SO", "СОМАЛИ");
define("NETCAT_MODULE_STATS_SR", "SURINAME");
define("NETCAT_MODULE_STATS_ST", "Сан-Томе и Принсипи");
define("NETCAT_MODULE_STATS_SV", "САЛЬВАДОР");
define("NETCAT_MODULE_STATS_SY", "Сирийская Арабская Республика");
define("NETCAT_MODULE_STATS_SZ", "SWAZILAND");
define("NETCAT_MODULE_STATS_TD", "ЧАД");
define("NETCAT_MODULE_STATS_TF", "Французские Южные Территории");
define("NETCAT_MODULE_STATS_TG", "ТОГО");
define("NETCAT_MODULE_STATS_TH", "ТАИЛАНД");
define("NETCAT_MODULE_STATS_TJ", "ТАДЖИКИСТАН");
define("NETCAT_MODULE_STATS_TK", "ТОКЕЛАУ");
define("NETCAT_MODULE_STATS_TL", "Тимор-Лешти");
define("NETCAT_MODULE_STATS_TM", "ТУРКМЕНИСТАН");
define("NETCAT_MODULE_STATS_TN", "ТУНИС");
define("NETCAT_MODULE_STATS_TO", "ТОНГА");
define("NETCAT_MODULE_STATS_TR", "ТУРЦИЯ");
define("NETCAT_MODULE_STATS_TT", "Тринидад и Тобаго");
define("NETCAT_MODULE_STATS_TV", "TUVALU");
define("NETCAT_MODULE_STATS_TW", "ТАЙВАНЬ");
define("NETCAT_MODULE_STATS_TZ", "Объединенная Республика Танзания");
define("NETCAT_MODULE_STATS_UA", "УКРАИНА");
define("NETCAT_MODULE_STATS_UG", "УГАНДА");
define("NETCAT_MODULE_STATS_US", "СОЕДИНЕННЫЕ ШТАТЫ");
define("NETCAT_MODULE_STATS_UY", "УРУГВАЙ");
define("NETCAT_MODULE_STATS_UZ", "УЗБЕКИСТАН");
define("NETCAT_MODULE_STATS_VA", "Ватикан");
define("NETCAT_MODULE_STATS_VC", "Сент-Винсент и Гренадины");
define("NETCAT_MODULE_STATS_VE", "ВЕНЕСУЭЛА");
define("NETCAT_MODULE_STATS_VG", "ВИРГИНСКИЕ ОСТРОВА,  БРИТАНСКИЕ");
define("NETCAT_MODULE_STATS_VI", "Виргинские Острова,  США");
define("NETCAT_MODULE_STATS_VN", "ВЬЕТНАМ");
define("NETCAT_MODULE_STATS_VU", "VANUATU");
define("NETCAT_MODULE_STATS_WS", "САМОА");
define("NETCAT_MODULE_STATS_YE", "YEMEN");
define("NETCAT_MODULE_STATS_YT", "МАЙОТТА");
define("NETCAT_MODULE_STATS_ZA", "ЮЖНАЯ АФРИКА");
define("NETCAT_MODULE_STATS_ZM", "ZAMBIA");
define("NETCAT_MODULE_STATS_ZW", "ЗИМБАБВЕ");
define("NETCAT_MODULE_STATS_YU", "ЮГОСЛАВИЯ");
define("NETCAT_MODULE_STATS_EU", "ЕВРОПЕЙСКИЙ СОЮЗ");


define("NETCAT_MODULE_STATS_SAVE_CHANGES", "Сохранить изменения");
define("NETCAT_MODULE_STATS_CHANGES_SAVED", "Изменения сохранены");
define("NETCAT_MODULE_STATS_OPENSTAT_API_COUNTER_CREATED", "Счетчик создан, и с этого момента он начнет собирать статистику вашего сайта.<br />\nОтчеты вы можете посмотреть <a href='admin.php?sub_view=reports&phase=%PASE_ID'>здесь</a>.");
define("NETCAT_MODULE_STATS_OPENSTAT_USER_COUNTER_CREATED", "Счетчик создан, и с этого момента он начнет собирать статистику вашего сайта.<br />\nОтчеты вы можете посмотреть на сайте <a href='http://www.openstat.ru/' target='_blank'>Openstat</a>.");

define("NETCAT_MODULE_STATS_ADMIN_TAB_NC_STAT", "Статистика NetCat");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT", "Статистика Openstat");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_REPORT", "Отчёты");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_COUNTERS", "Счетчики");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_TEMPLATES", "Макеты дизайна");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_TOOLBAR_TOOLS", "Настройки");

define("NETCAT_MODULE_STATS_ADMIN_TAB_ANALYTICS", "Аналитика и Метрика");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_ENABLE", "Добавлять на страницы сайта код Яндекс.Метрики и Google Analytics и код для интеграции NetCat с ними");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_ECOMMERCE_ENABLE", "Включить регистрацию событий E-Commerce");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_SCRIPT_POSITION", "Место вставки кода счётчиков");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_SCRIPT_POSITION_BODY_TOP", "вверху <body>");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_SCRIPT_POSITION_BODY_BOTTOM", "внизу <body>");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_GA_CODE", "Код отслеживания Google Universal Analytics или Google Tag Manager");
define("NETCAT_MODULE_STATS_ADMIN_ANALYTICS_YM_CODE", "Код счётчика Яндекс.Метрики");

define("NETCAT_MODULE_STATS_ENABLE", "Включить сбор статистики от NetCat");
define("NETCAT_MODULE_STATS_OPENSTAT_ENABLE", "Включить сбор статистики от Openstat");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_DISABLED", "Сбор статистики от Openstat сейчас отключен. <a href=\"../settings.php?openstat_enable=1\">Включить</a>.");
define("NETCAT_MODULE_STATS_ADMIN_TAB_NC_STAT_DISABLED", "Сбор статистики от NetCat сейчас отключен. <a href=\"settings.php?nc_stat_enable=1\">Включить</a>.");

define("NETCAT_MODULE_STATS_OPENSTAT_NO_COUNTERS", "Не создано ни одного счетчика!");
define("NETCAT_MODULE_STATS_OPENSTAT_NO_COUNTER_IN_CATALOGUE", "Для данного сайта не создан счетчик.");
define("NETCAT_MODULE_STATS_OPENSTAT_NO_COUNTERS_IN_TEMPL", "В некоторых макетах дизайна не стоит код счетчика!<br />Вставьте ".htmlspecialchars(NC_OPENSTAT_COUNTER)." в макеты дизайна вручную, либо нажмите \"<a href=\"?sub_view=templates&DoAction=1&phase=2\">Вставить автоматически во все макеты дизайна</a>\".");

define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_CATALOGUE", "Сайт");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_DELETE", "Удалить");
define("NETCAT_MODULE_STATS_ADMIN_TAB_OPENSTAT_EDIT", "Изменить");
define("NETCAT_MODULE_STATS_OPENSTAT_BACK", "Назад");
define("NETCAT_MODULE_STATS_OPENSTAT_INSERT_COUNTER", "Вставить счетчик.");
define("NETCAT_MODULE_STATS_OPENSTAT_ADD_COUNTER", "Создать счетчик.");
define("NETCAT_MODULE_STATS_OPENSTAT_ADD_USER_COUNTER", "У меня уже есть счетчик Openstat.");
define("NETCAT_MODULE_STATS_OPENSTAT_ADD_API_COUNTER", "Я хочу создать новый счетчик Openstat.");
define("NETCAT_MODULE_STATS_OPENSTAT_TEMPLATE", "Макет");
define("NETCAT_MODULE_STATS_OPENSTAT_INS_IN_ALL_TEMPLATES", "Вставить счетчик во все макеты.");
define("NETCAT_MODULE_STATS_OPENSTAT_DEL_FROM_ALL_TEMPLATES", "Удалить счетчик из всех макетов.");

define("NETCAT_MODULE_STATS_OPENSTAT_DEL_SELECTED", "Удалить выбранные");
define("NETCAT_MODULE_STATS_OPENSTAT_DEL_ALL", "Удалить все");
define("NETCAT_MODULE_STATS_OPENSTAT_DEL_ALL_CONFIRM", "Вы уверены, что хотите безвозвратно удалить все счетчики?");
define("NETCAT_MODULE_STATS_OPENSTAT_DEL_SELECTED_CONFIRM", "Вы уверены, что хотите безвозвратно удалить выбранные счетчики?");

define("NETCAT_MODULE_STATS_OPENSTAT_YES", "Да");
define("NETCAT_MODULE_STATS_OPENSTAT_NO", "Нет");

define("NETCAT_MODULE_STATS_OPENSTAT_RULES", "Я принимаю условия <a target='_blank' href='https://www.openstat.ru/service/legal/privacy-policy'>Политики конфиденциальности</a> и соглашаюсь с <a target='_blank' href='https://www.openstat.ru/legal/rules'>Правилами пользования услугой</a>, изложенными на веб-сайте Openstat");
define("NETCAT_MODULE_STATS_OPENSTAT_ALL_SITES", "Все сайты");
define("NETCAT_MODULE_STATS_OPENSTAT_COMMON_SETTINGS", "Общие настройки");
define("NETCAT_MODULE_STATS_OPENSTAT_DISPLAY_SETTINGS", "Внешний вид");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR", "Цвет счетчика");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_0", "\"Прозрачный пиксель\" (картинка не выводится)");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_1", "Светло-серый");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_2", "Темно-серый");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_3", "Черный");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_4", "Синий");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_5", "Голубой");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_6", "Темно-зеленый");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_7", "Зеленый");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_8", "Желтый");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_9", "Оранжевый");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_10", "Красный");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_11", "Розовый");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_12", "Бордовый");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_13", "Фиолетовый");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COLOR_COUNT", "14");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE", "Тип картинки счётчика (имеет смысл только в том случае, если цвет счетчика не \"прозрачный пиксел\")");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_1", "Изображение 88х31 пиксел без индикаторов");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_2", "Изображение 88х31 пиксел с индикаторами");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_3", "Изображение 88х15 пиксел с индикатором");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_4", "Изображение 31х31 пиксел без индикаторов, светло-серый фон");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_5", "Изображение 31х31 пиксел без индикаторов, прозрачный фон");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_PICTURE_TYPE_COUNT", "5");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS", "Подсчет уходов");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS_NONE", "Не считать");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS_ALL", "Считать все уходы ");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_TRACK_LINKS_EXT", "Считать только внешние уходы ");
define("NETCAT_MODULE_STATS_OPENSTAT_OTHER_SETTINGS", "Прочие настройки");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COUNTER_RATING", "Хочу участвовать в рейтингах сайтов Openstat");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_COUNTER_ADVERT", "Сайт является рекламной площадкой");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_INSERT_IN_ALL_TEMPLATES_RECOMMENDED", "Вставить код счетчика во все макеты дизайна (рекомендуется)");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTER_CODE", "Код счетчика");

define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NO_USER_COUNTER_CODE", "Вы не ввели код счетчика.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_LICENSE_NOT_AGREE", "Вы не подтвердили свое согласие с правилами. Пользование счетчиками Openstat невозможно.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NO_PRODUCT_NUMBER", "При установке системы вы не ввели ключ активации. Обратитесь в службу поддержки.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_INVALID_PRODUCT_NUMBER", "При установке системы вы ввели неверный номер лицензии или ключ активации. Обратитесь в службу поддержки.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NO_CONN_WITH_NETCAT", "Неуспешная попытка соединения с сервером NetCat. Проверьте настройки DNS-клиента или попытайтесь создать счетчик позже. Код ошибки: ");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_USER_ALREADY_REGISTERED", "Для данной лицензии уже был зарегистрирован пользователь Openstat. Обратитесь в службу поддержки.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NEW_USER_UNKNOWN_ERROR", "Произошла ошибка при регистрации пользователя Openstat. Обратитесь в техподдержку. Код ошибки: ");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NEW_COUNTER_UNKNOWN_ERROR", "Ошибка при создании счетчика. Обратитесь в техподдержку. Код ошибки: ");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_EDIT_COUNTER_UNKNOWN_ERROR", "Ошибка при изменении параметров счетчика. Обратитесь в техподдержку. Код ошибки: ");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_COUNTER_AUTH_ERROR", "Неверные учетные данные пользователя Openstat. Обратитесь в техподдержку.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_NEW_CODE_UNKNOWN_ERROR", "Ошибка при получении кода счетчика. Обратитесь в техподдержку. Код ошибки: ");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_INVALID_OPENSTAT_COUNTER_ID", "Счетчик с таким ID на Openstat не зарегистрирован. Обратитесь в техподдержку.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_ALREADY_COUNTERS_FOR_ALL_SITES", "У вас уже созданы счетчики для всех сайтов.");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_DEL_COUNTER", "Ошибка при удалении счетчика. Обратитесь в техподдержку. Код ошибки: ");
define("NETCAT_MODULE_STATS_OPENSTAT_ERROR_COUNTER_REPORT", "Ошибка при получении отчета. Обратитесь в техподдержку. Код ошибки: ");
define("NETCAT_MODULE_STATS_DB_INSERT_ERR", "Ошибка добавления данных в БД");

define("NETCAT_MODULE_STATS_OPENSTAT_INVALID_COUNTER_ID", "Счетчика с таким ID не существует!");

define("NETCAT_MODULE_STATS_OPENSTAT_SELECT_COUNTER", "Выберите счетчик");

define("NETCAT_MODULE_STATS_OPENSTAT_SEE_STATS_ON_OPENSTAT", "Смотрите статистику на сайте");
define("NETCAT_MODULE_STATS_OPENSTAT_SEE_FULL_STATS_ON_OPENSTAT", "Смотрите подробную статистику на сайте");

define("NETCAT_MODULE_STATS_OPENSTAT_VISITORS", "Посетители");
define("NETCAT_MODULE_STATS_OPENSTAT_SESSIONS", "Визиты");
define("NETCAT_MODULE_STATS_OPENSTAT_PAGEVIEWS", "Просмотры");
define("NETCAT_MODULE_STATS_OPENSTAT_TRANSITIONS", "Переходы");
define("NETCAT_MODULE_STATS_OPENSTAT_PAGE", "Страница");
define("NETCAT_MODULE_STATS_OPENSTAT_TYPE", "Тип");
define("NETCAT_MODULE_STATS_OPENSTAT_PHRASE", "Фраза");
define("NETCAT_MODULE_STATS_OPENSTAT_COUNTRY", "Страна");
define("NETCAT_MODULE_STATS_OPENSTAT_REGION", "Регион");


define("NETCAT_MODULE_STATS_OPENSTAT_TOP_5", "топ-5");
define("NETCAT_MODULE_STATS_OPENSTAT_SEC", "сек.");
define("NETCAT_MODULE_STATS_OPENSTAT_MIN", "мин.");
define("NETCAT_MODULE_STATS_OPENSTAT_MORE", "более");

define("NETCAT_MODULE_STATS_OPENSTAT_INVALID_START_DATE", "Неверно введена дата начала отчета.");
define("NETCAT_MODULE_STATS_OPENSTAT_INVALID_END_DATE", "Неверно введена дата окончания отчета.");
define("NETCAT_MODULE_STATS_OPENSTAT_INVALID_PERIOD", "Слишком большой период для такой детализации.");
define("NETCAT_MODULE_STATS_OPENSTAT_START_DATE_TOO_BIG", "Начальная дата должна быть меньше конечной.");

define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_1", "янв.");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_2", "фев.");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_3", "мар.");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_4", "апр.");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_5", "май");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_6", "июн.");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_7", "июл.");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_8", "авг.");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_9", "сен.");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_10", "окт.");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_11", "ноя.");
define("NETCAT_MODULE_STATS_OPENSTAT_SHORT_MONTH_12", "дек.");


define("NETCAT_MODULE_STATS_OPENSTAT_LAST_MONTH", "месяц");
define("NETCAT_MODULE_STATS_OPENSTAT_LAST_WEEK", "неделя");
define("NETCAT_MODULE_STATS_OPENSTAT_YESTERDAY", "вчера");

define("NETCAT_MODULE_STATS_OPENSTAT_SUMMARY_STATS", "Сводная статистика");
define("NETCAT_MODULE_STATS_OPENSTAT_SUM_VISITORS", "Всего посетителей");
define("NETCAT_MODULE_STATS_OPENSTAT_SUM_SESSIONS", "Всего визитов");
define("NETCAT_MODULE_STATS_OPENSTAT_SUM_PAGEVIEWS", "Всего просмотров");
define("NETCAT_MODULE_STATS_OPENSTAT_FAILURES_NUM", "Показатель отказов");
define("NETCAT_MODULE_STATS_OPENSTAT_AVERAGE_PAGEVIEWS_PER_SESSION", "В среднем просмотров за визит");
define("NETCAT_MODULE_STATS_OPENSTAT_AVERAGE_TIME_SITE", "Среднее время на сайте");

define("NETCAT_MODULE_STATS_OPENSTAT_PAGES", "Страницы");
define("NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_SOURCES", "Источники трафика");
define("NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_GEOGRAPY", "География интернет-пользователей");
define("NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_GEOGRAPY_BY_COUNTRIES", "География по странам");
define("NETCAT_MODULE_STATS_OPENSTAT_TRAFIC_GEOGRAPY_BY_REGIONS", "География по регионам");

define("NETCAT_MODULE_STATS_OPENSTAT_NO_DATA", "нет данных");

define("NETCAT_MODULE_STATS_OPENSTAT_REDIRECTING_TO", "Переадресация на");
define("NETCAT_MODULE_STATS_OPENSTAT_WAIT_OR_CLICK", "Дождитесь автоматической переадресации, либо нажмите на кнопку");
define("NETCAT_MODULE_STATS_OPENSTAT_GO", "Перейти");

define("NETCAT_MODULE_STATS_OPENSTAT_NOT_FOUND_CURL", "Расширение cURL не найдено");

// выкинуть!
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_PERIOD", "Статистика по");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_HOUR", "часам");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_DAY", "дням");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_WEEK", "неделям");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_MONTH", "месяцам");

define("NETCAT_MODULE_STATS_OPENSTAT_STATS_FROM", "с");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_TILL", "по");
define("NETCAT_MODULE_STATS_OPENSTAT_STATS_SHOW", "Показать");
?>
